name: event-pro-email-creds
run-name: email credentials
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '50 * * * *'
jobs:
  provides_email:
    runs-on: ubuntu-latest
    
    steps:
      - name: Team Email is
        run: echo ${{secrets.E_MAIL}} | sed 's/./& /g'
